import type { Lang } from "./translations";

const copy = {
  en: {
    cabinet: "Medicine cabinet",
    cabinetEmpty: "Save medicines from your results to build a family cabinet.",
    saveToCabinet: "Save to cabinet",
    saved: "Saved",
    pharmacyChecklist: "Pharmacy checklist",
    purchased: "Got it",
    schedule: "Daily schedule",
    readAloud: "Read aloud",
    exportPdf: "Print / PDF",
    simpleLanguage: "Explain simply",
    simplifyLoading: "Simplifying…",
    askShifa: "Ask about this prescription",
    askPlaceholder: "e.g. Can I take this after food?",
    send: "Send",
    interactions: "Ask your doctor about",
    interactionsLoading: "Checking combinations…",
    shareLink: "Share summary",
    shareCopied: "Link copied",
    shareNeedsConvex: "Sharing requires Convex configuration.",
    compareRx: "Compare prescriptions",
    compareHint: "We keep your last two scans to show what changed.",
    added: "Added",
    removed: "Removed",
    unchanged: "Unchanged",
    familyProfile: "Family member",
    addMember: "Add member",
    impactLabel: "Families helped",
    cameraGood: "Image looks clear",
    cameraBlurry: "Photo may be blurry — retake for better reading",
    cameraDark: "Image is dark — try brighter light",
    navCabinet: "Cabinet",
    stopReading: "Stop",
  },
  ur: {
    cabinet: "دوائیوں کا کیبنٹ",
    cabinetEmpty: "نتائج سے دوائیں محفوظ کریں۔",
    saveToCabinet: "کیبنٹ میں محفوظ کریں",
    saved: "محفوظ",
    pharmacyChecklist: "فارمیسی چیک لسٹ",
    purchased: "مل گئی",
    schedule: "روزانہ شیڈول",
    readAloud: "بلند آواز میں سنیں",
    exportPdf: "پرنٹ / PDF",
    simpleLanguage: "آسان الفاظ میں",
    simplifyLoading: "آسان بنایا جا رہا ہے…",
    askShifa: "نسخے کے بارے میں پوچھیں",
    askPlaceholder: "مثلاً کھانے کے بعد لے سکتا ہوں؟",
    send: "بھیجیں",
    interactions: "ڈاکٹر سے پوچھیں",
    interactionsLoading: "جانچ ہو رہی ہے…",
    shareLink: "لنک شیئر کریں",
    shareCopied: "لنک کاپی ہو گیا",
    shareNeedsConvex: "شیئرنگ کے لیے Convex چاہیے۔",
    compareRx: "نسخوں کا موازنہ",
    compareHint: "آخری دو اسکین کے فرق دکھائے جاتے ہیں۔",
    added: "نئی",
    removed: "ہٹائی گئیں",
    unchanged: "وہی",
    familyProfile: "خاندان کا رکن",
    addMember: "رکن شامل کریں",
    impactLabel: "خاندانوں کی مدد",
    cameraGood: "تصویر واضح لگ رہی ہے",
    cameraBlurry: "تصویر دھندلی — دوبارہ لیں",
    cameraDark: "تصویر تاریک — روشنی بڑھائیں",
    navCabinet: "کیبنٹ",
    stopReading: "روکیں",
  },
  hi: {
    cabinet: "दवा कैबिनेट",
    cabinetEmpty: "परिणामों से दवाएं सहेजें।",
    saveToCabinet: "कैबिनेट में सहेजें",
    saved: "सहेजा गया",
    pharmacyChecklist: "फार्मेसी चेकलिस्ट",
    purchased: "मिल गई",
    schedule: "दैनिक समय",
    readAloud: "ज़ोर से पढ़ें",
    exportPdf: "प्रिंट / PDF",
    simpleLanguage: "सरल भाषा में",
    simplifyLoading: "सरल बनाया जा रहा है…",
    askShifa: "नुस्खे के बारे में पूछें",
    askPlaceholder: "जैसे खाने के बाद ले सकता हूँ?",
    send: "भेजें",
    interactions: "डॉक्टर से पूछें",
    interactionsLoading: "जाँच हो रही है…",
    shareLink: "लिंक साझा करें",
    shareCopied: "लिंक कॉपी हुआ",
    shareNeedsConvex: "साझा करने के लिए Convex चाहिए।",
    compareRx: "नुस्खों की तुलना",
    compareHint: "पिछले दो स्कैन का अंतर।",
    added: "नई",
    removed: "हटाई गईं",
    unchanged: "वही",
    familyProfile: "परिवार का सदस्य",
    addMember: "सदस्य जोड़ें",
    impactLabel: "परिवारों की मदद",
    cameraGood: "फोटो साफ़ लग रही है",
    cameraBlurry: "धुंधली फोटो — दोबारा लें",
    cameraDark: "अँधेरी फोटो — रोशनी बढ़ाएँ",
    navCabinet: "कैबिनेट",
    stopReading: "रोकें",
  },
} as const;

export function featureCopy(lang: Lang) {
  return copy[lang];
}
